name: ci status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check-out repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install fbench
      run: poetry install

    - name: Run isort
      run: poetry run isort --check-only --line-length 79 --profile black ./

    - name: Run Black
      run: poetry run black --check --line-length 79 ./

    - name: Run Flake8
      run: poetry run flake8 --doctests --max-line-length 79 src/ tests/

    - name: Run pytest
      run: poetry run pytest tests/ --cov=fbench --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml

    - name: Build documentation
      run: poetry run make html --directory docs/
